import {images} from './Iconasset';
export const loginData = [
  {
    label: 'Email',
    flag: 'email',
    secureTextEntry: false,
    keyBoardType: 'email-address',
    error: false,
    errorText: 'Please provide valid email address',
    suffixIcon: false,
    prefixIcon: false,
  },
  {
    label: 'Password',
    flag: 'password',
    secureTextEntry: true,
    keyBoardType: 'default',
    error: false,
    errorText: 'Password must be greater than 8 characters',
    suffixIcon: false,
    prefixIcon: images.EYE,
  },
];

export const loginLinkData = [
  {
    text: '>  Forgot Yor Password?',
  },
  {
    text: '>  Need assistance confirming your account?',
  },
  {
    text: '>  Need assistance unlocking your account?',
  },
];

export const registerData = [
  {
    label: 'Organization',
    flag: 'organization',
    dropdownItem: [
      'ClecoTech Internatioal',
      'Accenture',
      'Infosys',
      'Microsoft',
      'TCS',
    ],
    secureTextEntry: false,
    keyBoardType: 'default',
    error: false,
    errorText: 'Organization name is required',
    suffixIcon: false,
    prefixIcon: images.DROPDOWN,
    value: '',
  },
  {
    label: 'First Name',
    flag: 'firstName',
    dropdownItem: null,
    secureTextEntry: false,
    keyBoardType: 'default',
    error: false,
    errorText: 'First name is Required',
    suffixIcon: false,
    prefixIcon: false,
    value: '',
  },
  {
    label: 'Last Name',
    flag: 'lastName',
    dropdownItem: null,
    secureTextEntry: false,
    keyBoardType: 'default',
    error: false,
    errorText: 'Last name is required',
    suffixIcon: false,
    prefixIcon: false,
    value: '',
  },
  {
    label: 'Email',
    flag: 'email',
    dropdownItem: null,
    secureTextEntry: false,
    keyBoardType: 'email-address',
    error: false,
    errorText: 'please provide valid email address',
    suffixIcon: false,
    prefixIcon: false,
    value: '',
  },
  {
    label: 'Password',
    flag: 'password',
    dropdownItem: null,
    secureTextEntry: true,
    keyBoardType: 'default',
    error: false,
    errorText: 'Password must be greater than 8 characters',
    suffixIcon: false,
    prefixIcon: images?.EYE,
    value: '',
  },
  {
    label: 'Confirm Password',
    flag: 'confirmPassword',
    dropdownItem: null,
    secureTextEntry: true,
    keyBoardType: 'default',
    error: false,
    errorText: 'Password not matched!',
    suffixIcon: false,
    prefixIcon: images?.EYE,
    value: '',
  },
  {
    label: 'Employee id',
    flag: 'employeeId',
    dropdownItem: null,
    secureTextEntry: false,
    keyBoardType: 'default',
    error: false,
    errorText: 'please enter a valid employee id',
    suffixIcon: false,
    prefixIcon: false,
    value: '',
  },
  {
    label: 'Designation',
    flag: 'designation',
    dropdownItem: null,
    secureTextEntry: false,
    keyBoardType: 'default',
    error: false,
    errorText: 'please enter your designation',
    suffixIcon: false,
    prefixIcon: false,
    value: '',
  },
];
